import json
import logging
import requests
from typing import Optional, Dict, Any, List
from datetime import datetime
from pydantic import BaseModel, Field, ValidationError

from app.core.base_strategy import SetupSignal, Candle, Indicators

logger = logging.getLogger(__name__)

# Config
LM_STUDIO_URL = "http://localhost:1234/v1/chat/completions"
LM_STUDIO_MODEL = "qwen/qwen3.5-9b"
REQUEST_TIMEOUT = 240  # seconds

class LLMVerdictSchema(BaseModel):
    verdict: str = Field(..., description="Must be exactly CONFIRM, REJECT, or MODIFY")
    reasoning: str = Field(..., description="2-3 sentence explanation of why this verdict was reached based on the technical context provided.")
    modified_sl: Optional[float] = Field(None, description="Suggested Stop Loss if verdict is MODIFY")
    modified_tp1: Optional[float] = Field(None, description="Suggested TP1 if verdict is MODIFY")
    modified_tp2: Optional[float] = Field(None, description="Suggested TP2 if verdict is MODIFY")

class LLMClient:
    """
    Client for interacting with the local LM Studio instance.
    Formats market context and parses the JSON response using Pydantic.
    """

    @staticmethod
    def _build_prompt_context(
        signal: SetupSignal,
        candles: list[Candle],
        indicators: Indicators,
        sr_zones: list[dict]
    ) -> str:
        """
        Constructs the system/user prompt combining the setup and the raw data.
        Limits the candle data to the last 30 to preserve context windows.
        """
        # Take the last 30 candles
        recent_candles = candles[-30:] if len(candles) >= 30 else candles
        candle_text = "Recent 30 Candles (OHLCV):\n"
        for c in recent_candles:
            candle_text += f"{c.open_time.strftime('%Y-%m-%d %H:%M:%S')} - O:{c.open} H:{c.high} L:{c.low} C:{c.close} V:{c.volume}\n"

        # Indicators text
        ind_text = (
            f"Indicators (Current):\n"
            f"RSI(14): {indicators.rsi_14}\n"
            f"MACD Line: {indicators.macd_line}, Signal: {indicators.macd_signal}, Hist: {indicators.macd_histogram}\n"
            f"EMA 9: {indicators.ema_9}, EMA 21: {indicators.ema_21}, EMA 50: {indicators.ema_50}, EMA 200: {indicators.ema_200}\n"
            f"Bollinger Bands: U:{indicators.bb_upper} M:{indicators.bb_middle} L:{indicators.bb_lower}\n"
        )

        # S/R Zones text
        sr_text = "Proximity S/R Zones:\n"
        for idx, z in enumerate(sr_zones[:5]): # limit to 5
            sr_text += f"Zone {idx+1}: {z.get('zone_type')} at {z.get('price_level')} (Score: {z.get('strength_score', 0):.2f})\n"

        # Signal Context
        signal_text = json.dumps(signal.to_dict(), indent=2)

        prompt = (
            f"You are an elite quantitative crypto trading analyst. Your job is to review a trade setup "
            f"generated by an algorithmic strategy and decide whether to CONFIRM, REJECT, or MODIFY the signal.\n\n"
            f"### Context ###\n"
            f"Pair: {signal.symbol}\n"
            f"Timeframe: {signal.timeframe}\n"
            f"Direction: {signal.direction}\n"
            f"Strategy: {signal.strategy_name}\n\n"
            f"{ind_text}\n"
            f"{sr_text}\n"
            f"{candle_text}\n"
            f"### Algorithmic Signal Props ###\n"
            f"{signal_text}\n\n"
            f"Evaluate the market structure, support/resistance bands, momentum, and the strategy condition.\n"
            f"Respond ONLY in valid JSON matching the following schema. No markdown formatting, just pure JSON:\n"
            f"{{\n"
            f"  \"verdict\": \"CONFIRM|REJECT|MODIFY\",\n"
            f"  \"reasoning\": \"string\",\n"
            f"  \"modified_sl\": float|null,\n"
            f"  \"modified_tp1\": float|null,\n"
            f"  \"modified_tp2\": float|null\n"
            f"}}\n"
        )
        return prompt

    @staticmethod
    def evaluate_signal(
        signal: SetupSignal,
        candles: list[Candle],
        indicators: Indicators,
        sr_zones: list[dict]
    ) -> Optional[LLMVerdictSchema]:
        """
        Sends the signal and context to LM Studio synchronously.
        Returns the parsed LLMVerdictSchema or None on failure.
        """
        prompt = LLMClient._build_prompt_context(signal, candles, indicators, sr_zones)
        
        payload = {
            "model": LM_STUDIO_MODEL,
            "messages": [
                {"role": "system", "content": "You are a quantitative trading system generating JSON outputs based on raw market data."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.2, # Deterministic reasoning
            "max_tokens": 800,
            "stream": False
        }

        try:
            resp = requests.post(LM_STUDIO_URL, json=payload, timeout=REQUEST_TIMEOUT)
            resp.raise_for_status()
            data = resp.json()
            
            # Extract content
            content = data.get("choices", [])[0].get("message", {}).get("content", "").strip()
            
            # Defensive strip of markdown codeblocks occasionally generated by LLMs
            if content.startswith("```json"):
                content = content[7:]
            if content.endswith("```"):
                content = content[:-3]
            content = content.strip()

            # Parse with Pydantic
            parsed = LLMVerdictSchema.model_validate_json(content)
            
            # Ensure proper string matching
            if parsed.verdict not in ('CONFIRM', 'REJECT', 'MODIFY'):
                logger.error(f"LLM produced invalid verdict: {parsed.verdict}")
                return None
                
            return parsed
            
        except requests.exceptions.RequestException as e:
            logger.error(f"LM Studio connection error: {str(e)}")
            return None
        except ValidationError as e:
            logger.error(f"LLM JSON Schema validation error: {str(e)}\nRaw Response: {content}")
            return None
        except Exception as e:
            logger.error(f"Unexpected error in LLM evaluate_signal: {str(e)}")
            return None

    @staticmethod
    def ping_status() -> bool:
        """
        Pings the LM Studio /v1/models endpoint to verify it is online.
        """
        url = LM_STUDIO_URL.replace("/chat/completions", "/models")
        try:
            resp = requests.get(url, timeout=3)
            return resp.status_code == 200
        except requests.exceptions.RequestException:
            return False
